default_agent: medical_terminology_agent_v2
agents:
  medical_terminology_agent:
    name: medical_terminology_agent
    language: python
    node_version: '20'
    entrypoint: main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: .
    aws:
      execution_role: arn:aws:iam::225602822766:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-4067720e66
      execution_role_auto_create: false
      account: '225602822766'
      region: us-east-1
      ecr_repository: 225602822766.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-medical_terminology_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-medical_terminology_agent-builder
      execution_role: arn:aws:iam::225602822766:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-4067720e66
      source_bucket: bedrock-agentcore-codebuild-sources-225602822766-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: medical_terminology_agent_mem-w2dPRsBfZR
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:225602822766:memory/medical_terminology_agent_mem-w2dPRsBfZR
      memory_name: medical_terminology_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  medical_terminology_agent_v2:
    name: medical_terminology_agent_v2
    language: python
    node_version: '20'
    entrypoint: main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: .
    aws:
      execution_role: arn:aws:iam::225602822766:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-ba0b022310
      execution_role_auto_create: false
      account: '225602822766'
      region: us-east-1
      ecr_repository: 225602822766.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-medical_terminology_agent_v2
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: medical_terminology_agent_v2-aH2mqlHQR9
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:225602822766:runtime/medical_terminology_agent_v2-aH2mqlHQR9
      agent_session_id: 8fabf472-912c-47bf-9dac-001cbb766d08
    codebuild:
      project_name: bedrock-agentcore-medical_terminology_agent_v2-builder
      execution_role: arn:aws:iam::225602822766:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-ba0b022310
      source_bucket: bedrock-agentcore-codebuild-sources-225602822766-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
