"""
Amazon Bedrock service for Medical Terminology Agent.
"""

import json
import os

import boto3


class BedrockService:
    """
    Handles communication with Amazon Bedrock.
    """

    def __init__(self):
        """
        Initialize Bedrock client.
        """

        self.client = boto3.client(
            service_name="bedrock-runtime",
            region_name=os.getenv(
                "AWS_REGION",
                "us-east-1",
            ),
        )

        self.model_id = os.getenv(
            "BEDROCK_MODEL_ID",
            "amazon.nova-micro-v1:0",
        )

    def explain_term(self, medical_term: str) -> str:
        """
        Generate an educational explanation for a medical term.

        Args:
            medical_term: Medical terminology entered by user.

        Returns:
            Educational explanation generated by Amazon Bedrock.
        """

        prompt = (
            f"You are a medical terminology assistant. "
            f"Explain the medical term '{medical_term}' in simple language. "
            f"Limit your response to 2-3 sentences. "
            f"Do not diagnose diseases or recommend treatments. "
            f"Provide educational information only."
        )

        request_body = {
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "text": prompt
                        }
                    ]
                }
            ]
        }

        response = self.client.invoke_model(
            modelId=self.model_id,
            body=json.dumps(request_body),
            contentType="application/json",
            accept="application/json",
        )

        response_body = json.loads(response["body"].read())

        return response_body["output"]["message"]["content"][0]["text"]